MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  
  # Loss weights
  ID_LOSS_WEIGHT: 0.25
  TRIPLET_LOSS_WEIGHT: 1.0
  I2T_LOSS_WEIGHT: 1.0
  # META_LOSS_WEIGHT: 0.5  # Weight for metadata enhanced features
  
  # Camera/View embedding
  SIE_CAMERA: True
  SIE_COE: 1.0

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  # Stage 1: Train metadata text generator
  STAGE1:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00015
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 50
    CHECKPOINT_PERIOD: 50
    LOG_PERIOD: 10
    WARMUP_EPOCHS: 5

  # Stage 2: Train full model with metadata
  STAGE2:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.000001
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY: 0.0001
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: False
    MAX_EPOCHS: 45
    CHECKPOINT_PERIOD: 45
    LOG_PERIOD: 10
    EVAL_PERIOD: 45
    BIAS_LR_FACTOR: 2
    STEPS: [30, 50]
    GAMMA: 0.1

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

DATASETS:
  NAMES: ("stoat")
  ROOT_DIR: ("/data/yil708/Code-CLIP-ReID/Meta-Feature-Adapter/data/")

OUTPUT_DIR: "/data/yil708/Code-CLIP-ReID/Meta-Feature-Adapter/scripts/Stoat/CLIP-ReID"

# CUDA_VISIBLE_DEVICES=1 python train_metareid.py --config_file configs/animal/vit_metareid.yml